import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="wrap" style={{ paddingLeft: "275px" }}>
          <div
            className="sidebar bg-white"
            style={{
              position: "fixed",
              width: "275px",
              top: "0",
              left: "0",
              height: "100vh",
              paddingTop: "75px",
            }}
          >
            <Link href="/">Home</Link>
            <br />
            <Link href="/about">About</Link>
          </div>
          <nav className="navbar navbar-dark fixed-top bg-dark">
            <div className="container-fluid">
              <a className="navbar-brand" href="#">
                Default
              </a>
            </div>
          </nav>
          <div className="d-flex">
            <div
              className=""
              style={{
                // height: "calc(100vh - 80px)",
                backgroundColor: "#fff",
                color: "black",
              }}
            ></div>
            <div className="">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
