import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap-icons/font/bootstrap-icons.min.css";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="wrap" style={{ paddingLeft: "275px" }}>
          <div
            className="sidebar bg-white"
            style={{
              position: "fixed",
              width: "275px",
              top: "0",
              left: "0",
              height: "100vh",
              paddingTop: "75px",
            }}
          >
            <Link href="/">Home</Link>
            <br />
            <Link href="/about">About</Link>
          </div>


<div className="navbar">
          <nav className="navbar navbar-dark fixed-top bg-white" style={{ paddingRight: "50px",  paddingLeft: "50px" }}> 
          {/* navbar-dark fixed-top bg-light */}
            <div className="namelogo">
    <a className="navbar-brand" href="#">
      <img className="img-fluid" src="./images/pinkSale.png" alt="logo" style={{ height: '40px', width: '40px' }}  />
      <span style={{ color: "black" }}>   PinkSale</span>
    </a></div>
          <div className="buttons d-flex align-items-center"> 
    
          <button type="button" className="btn rounded-pill  mx-1"style={{ backgroundColor: "#f3f3f4", color: "black" }}><i className="bi bi-graph-up"></i>   dexview.com</button>
          <button type="button" className="btn rounded-pill  mx-1"style={{ backgroundColor: "#f3f3f4", color: "black" }}><img 
          src="./images/bsc.png"
          alt="Icon"
          style={{ height: '20px', width: '20px' }}  
        />  BSC MAINNET</button>
          <button type="button" className="btn rounded-pill  mx-1"style={{ backgroundColor: "#fdeaf1", color: "#f95997" }}>Connect</button>

          {/* <a className="nav-link mx-2" href="/"><span style={{ color: "black" }}>dexview.com</span></a>
          <a className="nav-link mx-2" href="/"><span style={{ color: "black" }}>BSC Mainnet</span></a>
          <a className="nav-link mx-2" href="/"><span style={{ color: "black" }}>Connect</span></a> */} 
          </div>  
         </nav></div> 

          {/* <nav className="navbar navbar-dark fixed-top bg-dark">
            <div className="container-fluid">
              <a className="navbar-brand" href="#">
                Default
              </a>
            </div>
          </nav> */}
    
          <div className="d-flex">
            <div
              className=""
              style={{
                // height: "calc(100vh - 80px)",
                backgroundColor: "#fff",
                color: "black",
              }}
            ></div>
            <div className="">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
